version: "3.0"

services:
  web:
    build: .
    entrypoint: >
      bash -c "
      rm -f tmp/pids/server.pid
      && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/src/app
    depends_on:
      - db
      - redis
    links:
      - "db:db"
      - "redis:redis"
  db:
    image: postgres:11
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:5.0
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    depends_on:
      - db
      - redis
      - web
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/src/app
    env_file:
      - .env

volumes:
  db_data:
  redisdata:
